import { useMemo } from "react";
import type { HeadersFunction } from "react-router";
import { boundary } from "@shopify/shopify-app-react-router/server";
import { TitleBar, useAppBridge } from "@shopify/app-bridge-react";
import { useState, useEffect } from 'react';
import {CalloutCard} from '@shopify/polaris';
import {Page, Layout, LegacyCard} from '@shopify/polaris';

export default function Index() {
  const shopify = useAppBridge();
  const [shop, setShop] = useState<string>("");
  const [metaentryurl, setMetaentryurl] = useState<string>("");
  const [giftcardurl, setGiftcardurl] = useState<string>("");

  useEffect(() => {
    setShop(shopify.config.shop ?? "");
    const storeDomain = shopify?.config?.shop?.replace(".myshopify.com", "");
    setMetaentryurl(`https://admin.shopify.com/store/${storeDomain}/content/metaobjects/entries/jci_gift_card`);
    setGiftcardurl(`https://admin.shopify.com/store/${storeDomain}/gift_cards?source=api_client`);
  }, [shopify]);

  return (
    <Page title="JCI Gift Card Automation">
      <Layout>
        <Layout.Section>

          {/* Gift Condition Card */}
          <CalloutCard
            title="🎁 Gift Condition Rules"
            illustration="/gift-card.png"
            primaryAction={{
              target: "_parent",
              content: "Edit Condition",
              url: metaentryurl,
            }}
          >
            <p>
              Create and manage <strong>Gift Conditions</strong> that
              automatically issue a gift card based on the customer’s order
              total. When an order amount is between your defined{" "}
              <strong>Min</strong> and <strong>Max</strong> values, a{" "}
              <strong>Gift Card</strong> is created automatically with the
              specified value.
            </p>
          </CalloutCard>

          {/* Gift Card List Card */}
          <CalloutCard
            title="💳 Gift Cards Created by the App"
            illustration="/customizer.svg"
            primaryAction={{
              target: "_parent",
              content: "View Gift Cards",
              url: giftcardurl,
            }}
          >
            <p>
              All gift cards generated by this app appear under your Shopify
              <strong> Gift Cards</strong> tab. Each card includes its unique
              code, balance, and creation date, helping you track automated
              rewards issued to customers.
            </p>
          </CalloutCard>

        </Layout.Section>
      </Layout>
    </Page>
  );
}

export const headers: HeadersFunction = (headersArgs) => {
  return boundary.headers(headersArgs);
};